Repository Vivid-Project/frontend, pull requests merged in 2021-03, with the labels that each got.

#43 Fix/buttons
  package-lock.json
  package.json
  src/App.js
  src/common/TonesOverTime.js
  src/modules/Dashboard/Dashboard.js
  src/modules/Dashboard/Dashboard.test.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/Header/Header.js
  src/modules/NewDream/NewDream.js
Labels: Frontend, Styling

#44 Fix/card tone
  src/API/APIcalls.js
  src/common/ToneGraph.js
  src/modules/DreamCard/DreamCard.js
  src/modules/DreamCard/DreamCard.test.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/Login/Login.js
Labels: Frontend, Styling

#45 Feature/tone time tweaks
  src/API/APIcalls.js
  src/common/TonesOverTime.js
  src/modules/Login/Login.js
Labels: Frontend, enhancement

#46 Fix/login condition
  src/API/APIcalls.js
  src/modules/Dashboard/Dashboard.test.js
  src/modules/DreamCard/DreamCard.test.js
  src/modules/Login/Login.js
Labels: Frontend, enhancement

#47 Fix/journal dream sorting
  src/Analytics/ToneBar.js
  src/Analytics/ToneGraph.js
  src/Analytics/TonesOverTime.js
  src/modules/Analytics/Analytics.js
  src/modules/Dashboard/Dashboard.js
  src/modules/DreamCard/DreamCard.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/Login/Login.js
  src/modules/NewDream/NewDream.js
Labels: Frontend, enhancement

#48 Feature/integration testing
  cypress.json
  cypress/fixtures/dreamResponseData.json
  cypress/integration/App.integration.test.js
  cypress/plugins/index.js
  cypress/screenshots/All Integration Specs/my-image.png
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/modules/Header/Header.js
  src/modules/NewDream/NewDream.js
Labels: Frontend, Testing

#49 Fix/unit testing
  src/Analytics/ToneBar.js
  src/Analytics/ToneGraph.js
  src/Analytics/TonesOverTime.js
  src/modules/Dashboard/Dashboard.js
  src/modules/Dashboard/Dashboard.test.js
  src/modules/DreamCard/DreamCard.js
  src/modules/DreamCard/DreamCard.test.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/DreamJournal/DreamJournal.test.js
  src/modules/Header/Header.js
  src/modules/Header/Header.test.js
  src/modules/Login/Login.js
  src/modules/Login/Login.test.js
  src/modules/NewDream/NewDream.js
  src/modules/NewDream/NewDream.test.js
Labels: Frontend, Styling, Testing

#53 Fix/desktop view formatting
  src/Analytics/TonesOverTime.js
  src/App.js
  src/modules/Dashboard/Dashboard.js
  src/modules/DreamJournal/DreamJournal.js
Labels: Frontend, Styling

#61 Feature/signup tests
  cypress/integration/App.integration.test.js
  package-lock.json
  package.json
  src/modules/Dashboard/Dashboard.js
  src/modules/DreamJournal/DreamJournal.test.js
  src/modules/Header/Header.js
  src/modules/Login/Login.js
  src/modules/Login/Login.test.js
  src/modules/NewDream/NewDream.js
  src/modules/SignUp/SignUp.js
  src/modules/SignUp/SignUp.test.js
Labels: Frontend, Styling, Testing

#62 Feature/dream tags
  src/API/APIcalls.js
  src/modules/DreamCard/DreamCard.js
  src/modules/DreamCard/DreamCard.test.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/NewDream/NewDream.js
  src/modules/NewDream/NewDream.test.js
Labels: Frontend, enhancement
