Repository Vivid-Project/frontend, pull requests merged in 2021-02, with the labels that each got.

#12 Feature/init setup
  package-lock.json
  package.json
  public/logo192.png
  public/logo512.png
  src/App.js
  src/index.js
  src/logo.svg
  src/modules/Analytics/Analytics.js
  src/modules/Dashboard/Dashboard.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/Login/Login.js
  src/modules/NewDream/NewDream.js
  src/reportWebVitals.js
Labels: Frontend, enhancement

#15 Feature/dream entry form
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/modules/NewDream/NewDream.js
Labels: Frontend, enhancement

#16 Feature/dream- card
  package-lock.json
  package.json
  src/data/fakeDreams.js
  src/modules/DreamJournal/DreamJournal.js
Labels: Frontend

#17 Feature/login buildout
  package-lock.json
  src/App.css
  src/assets/login-landing-back.jpg
  src/modules/Login/Login.js
  src/modules/NewDream/NewDream.js
  src/themes/theme.js
Labels: Frontend, enhancement

#21 Feature/app bar
  package.json
  src/App.css
  src/App.js
  src/modules/Header/Header.js
  src/modules/Login/Login.js
Labels: Frontend, enhancement

#27 Feature/testing
  .travis.yml
  package-lock.json
  package.json
  src/App.test.js
  src/data/fakeDreams.js
  src/modules/Dashboard/Dashboard.js
  src/modules/Dashboard/Dashboard.test.js
  src/modules/DreamCard/DreamCard.js
  src/modules/DreamCard/DreamCard.test.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/NewDream/NewDream.js
  src/modules/NewDream/NewDream.test.js
Labels: Frontend, Testing

#32 Add cond formatting for offline message
  src/modules/Header/Header.js
Labels: Frontend, Styling, enhancement

#34 Fix/implement user login api
  src/API/APIcalls.js
  src/data/fakeDreams.js
  src/data/fakeUser.js
  src/modules/Dashboard/Dashboard.js
  src/modules/Dashboard/Dashboard.test.js
  src/modules/DreamCard/DreamCard.js
  src/modules/DreamCard/DreamCard.test.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/Header/Header.js
  src/modules/Login/Login.js
  src/modules/NewDream/NewDream.js
  src/modules/NewDream/NewDream.test.js
Labels: Frontend, Testing, enhancement

#37 Correct capitalization of mostRecent variable
  src/modules/Dashboard/Dashboard.js
Labels: Frontend, bug

#39 Feature/analytics graphs
  src/API/APIcalls.js
  src/common/TonesOverTime.js
  src/data/fakeDreams.js
  src/modules/Analytics/Analytics.js
  src/modules/Dashboard/Dashboard.js
  src/modules/DreamCard/DreamCard.js
  src/modules/DreamJournal/DreamJournal.js
  src/modules/Login/Login.js
  src/modules/NewDream/NewDream.js
Labels: Frontend, enhancement

#42 Install graph timeline selector for user
  src/common/TonesOverTime.js
Labels: Frontend, enhancement
